CREATE TABLE employee (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(120),
    role VARCHAR(120),
    departement VARCHAR(120),
    mobile VARCHAR(32),
    date_embauche DATE,
    email VARCHAR(160),
    genre VARCHAR(20),
    adresse VARCHAR(255),
    photo TEXT,
    statut VARCHAR(20),
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_employee_statut CHECK (statut IN ('ACTIF', 'INACTIF', 'EN_CONGE'))
);

CREATE TABLE user_app (
    user_app_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120),
    email VARCHAR(160) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_app_email UNIQUE (email),
    CONSTRAINT chk_user_app_role CHECK (role IN ('ADMIN', 'VIEWER', 'RECOGNITION_CLIENT'))
);

CREATE TABLE presence_jour (
    presence_jour_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_employee_id BIGINT,
    first_in TIME,
    break_time TIME,
    resume_time TIME,
    last_out TIME,
    total_heures NUMERIC(21,0),
    statut VARCHAR(20),
    note VARCHAR(255),
    shift VARCHAR(255),
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_presence_jour_employee FOREIGN KEY (employee_employee_id) REFERENCES employee (employee_id),
    CONSTRAINT chk_presence_jour_statut CHECK (statut IN ('TERMINE', 'ABSENT', 'PRESENT', 'EN_PAUSE'))
);

CREATE TABLE entree_recente (
    entree_recente_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_employee_id BIGINT,
    heure TIME,
    portail VARCHAR(255),
    date DATE,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_entree_recente_employee FOREIGN KEY (employee_employee_id) REFERENCES employee (employee_id)
);

CREATE INDEX idx_presence_jour_employee_creation_date
    ON presence_jour (employee_employee_id, creation_date);

CREATE INDEX idx_entree_recente_employee_date_heure
    ON entree_recente (employee_employee_id, date, heure);
