package ma.dream.case_backend.enums;

public enum ApiErrorCode {
    REQUEST_VALIDATION_FAILED,
    REQUEST_BODY_INVALID,
    RESOURCE_NOT_FOUND,
    BAD_CREDENTIALS,
    ACCESS_DENIED,
    AUTHENTICATION_REQUIRED,
    BUSINESS_RULE_VIOLATION,
    DUPLICATE_RESOURCE,
    INTERNAL_SERVER_ERROR
}
